name: VibeU
options:
  bundleIdPrefix: com.vibeu
  deploymentTarget:
    iOS: 26.0
targets:
  VibeU:
    type: application
    platform: iOS
    sources:
      - VibeU
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vibeu.VibeU
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: VibeU/Info.plist
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseStorage
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.15.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
